# Generated by Django 5.2.4 on 2025-08-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('eleve', 'Élève'), ('prof', 'Professeur'), ('admin', 'Administrateur'), ('investisseur', 'investisseur')], default='eleve', max_length=100, null=True),
        ),
    ]
