# Generated by Django 5.2.4 on 2025-08-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0003_feedbackcorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='correction_enabled',
            field=models.BooleanField(default=True, verbose_name='Autoriser la soumission/correction'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='message_bloquant',
            field=models.TextField(blank=True, default='', verbose_name='Message personnalisé de blocage'),
        ),
    ]
