# Generated by Django 5.2.4 on 2025-08-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0005_customuser_device_id_deviceconnectionhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemigrationrequest',
            name='user_date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
