# Generated by Django 5.2.4 on 2025-08-28 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0006_devicemigrationrequest_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoumissionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('extraction', 'Extraction texte'), ('analyse_ia', 'Analyse IA'), ('generation_graphiques', 'Génération graphiques'), ('formatage_pdf', 'Formatage PDF'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_attente', max_length=200)),
                ('progression', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('resultat_json', models.JSONField(blank=True, null=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correction.demandecorrection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
