# Generated by Django 5.2.4 on 2025-08-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0007_soumissionia'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecorrection',
            name='enonce_texte',
            field=models.TextField(blank=True, default=''),
        ),
    ]
