# Generated by Django 5.2.4 on 2025-12-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0008_demandecorrection_enonce_texte'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumissionia',
            name='exercice_index',
            field=models.IntegerField(blank=True, help_text='Index de l’exercice traité par ce ticket', null=True, verbose_name='Index exercice'),
        ),
    ]
