# Generated by Django 5.2.4 on 2025-12-28 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0009_soumissionia_exercice_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrigePartiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_exercice', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(upload_to='corriges/')),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corriges', to='correction.soumissionia')),
            ],
        ),
    ]
