# Generated by Django 5.2.4 on 2025-12-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0010_alter_customuser_role_corrigepartiel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandecorrection',
            name='corrigé',
        ),
        migrations.RemoveField(
            model_name='demandecorrection',
            name='enonce_texte',
        ),
    ]
