# Generated by Django 5.2.4 on 2026-01-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0011_remove_demandecorrection_corrigé_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecorrection',
            name='exercices_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandecorrection',
            name='nom_fichier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
