# Generated by Django 5.2.4 on 2026-01-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0012_demandecorrection_exercices_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_whatsapp', models.URLField(help_text='Lien WhatsApp complet (ex: https://wa.me/2376XXXXXXX?text=Bonjour)', max_length=500)),
                ('message_accueil', models.TextField(default="Bonjour, je suis intéressé par vos services CIS. Pouvez-vous m'aider ?", help_text="Message par défaut qui s'affichera dans WhatsApp")),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact WhatsApp',
                'verbose_name_plural': 'Contact WhatsApp',
            },
        ),
    ]
