# Generated by Django 5.2.4 on 2026-01-15 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnement', '__first__'),
        ('resources', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('nom_affiche', models.CharField(max_length=64)),
                ('operateur', models.CharField(max_length=64)),
                ('type_paiement', models.CharField(choices=[('INTERNE', 'Paiement interne (via app)'), ('EXTERNE', 'Paiement externe (redirection)')], default='INTERNE', max_length=10)),
                ('ussd', models.CharField(blank=True, max_length=64)),
                ('service_code', models.CharField(blank=True, help_text='Code Touchpay à passer (ex: PAIEMENTMARCHAND_MTN_CM)', max_length=100, null=True)),
                ('lien_externe', models.URLField(blank=True, help_text='URL de redirection', max_length=500, null=True)),
                ('instructions_externes', models.TextField(blank=True, default="Cliquez sur le lien suivant pour payer. Après paiement, faites une capture d'écran du message de confirmation et envoyez-la par WhatsApp.", help_text='Instructions pour les paiements externes')),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('extra_config', models.JSONField(blank=True, null=True)),
                ('priorite', models.IntegerField(default=1, help_text="Ordre d'affichage")),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='resources.pays')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('phone', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(default='INITIATED', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonnement.subscriptiontype')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paiement.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
