# Generated by Django 5.2.4 on 2026-01-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='instructions_externes',
            field=models.TextField(blank=True, default="Cliquez sur le lien suivant pour payer. Après paiement, faites une capture d'écran du message de paiement et envoyez-la par WhatsApp.", help_text='Instructions pour les paiements externes'),
        ),
    ]
