# Generated by Django 5.2.4 on 2026-03-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0002_alter_paymentmethod_instructions_externes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='type_paiement',
            field=models.CharField(choices=[('INTERNE', 'Paiement interne (via app)'), ('EXTERNE', 'Paiement externe (redirection)'), ('IFRAME', 'Paiement par iframe intégré')], default='INTERNE', max_length=10),
        ),
    ]
